### ISSUE TITLE
Specification of R2_Leading_Trim_ODN

### ISSUE THREAD

**Issue by racng** [cnobles/iGUIDE#87]
In the `simulation.config.yaml`, R2_Leading_Trim_ODN is specified as `ACGCGA`. However, should it be `TACGCGA` instead? Since this would be the full subsequence of the iGUIDE that is not primed by the GSP2_neg_Nuc_off primer from the iGUIDE paper? Or is this shortened on purpose?

```yaml
R1_Leading_Trim : "."
R1_Overreading_Trim : "TCGCGTATACCGTTATTAACATATGACAACTCAA"
R2_Leading_Trim : "TTGAGTTGTCATATGTTAATAACGGTAT"
R2_Leading_Trim_ODN : "ACGCGA"
R2_Overreading_Trim : "AGATCGGAAGAGCGTCGTGT"
```

![image](https://github.com/user-attachments/assets/9e074de0-ff42-4bfd-87c4-c37dbd74368d)
