### ISSUE TITLE
iguide_evaluation failed

### ISSUE THREAD

**Issue by cedarice** [cnobles/iGUIDE#90]
Whether using BLAT or BWA aligner, the following error is reported during the `iguide_evaluation` step.
```
Error in `$<-.data.frame`(`*tmp*`, annotation, value = " ") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
```

**Comment by cnobles** [comment]
Hi @cedarice,

Could you provide more context around the error. Which dataset are you running (simulation or your own)? Does this happen for a single sample or each sample? You can use the "--keep-going" option when you run iguide (snakemake) to keep executing other jobs even if one errors out. I will continue to process until dependencies are not met. 

Also have you updated to the recent release (just put it out, v1.1.1). I hadn't ran into this issue in the CI tests or when I was running it locally.

Happy holidays!

**Comment by cedarice** [comment]
> Hi @cedarice,
> 
> Could you provide more context around the error. Which dataset are you running (simulation or your own)? Does this happen for a single sample or each sample? You can use the "--keep-going" option when you run iguide (snakemake) to keep executing other jobs even if one errors out. I will continue to process until dependencies are not met.
> 
> Also have you updated to the recent release (just put it out, v1.1.1). I hadn't ran into this issue in the CI tests or when I was running it locally.
> 
> Happy holidays!

Thanks for your kind response.  The dataset I'm using consists of single-sample data that belongs to me. The received data has already been demultiplexed, with each sample including R1, R2, I1, and I2 fastq files. Below is my `config.yml` file.
```yaml
# Run configuration
Run_Name : "B2M-39"
Sample_Info : "sampleInfo/B2M-39.sampleInfo.csv"
Supplemental_Info : "."
Ref_Genome : "hg38"
Aligner : "bwa"
UMItags : FALSE
Abundance_Method : "Fragment"
# Sequence files
Seq_Path : "fastq_files"
R1: "B2M-39.R1.fastq.gz"
R2: "B2M-39.R2.fastq.gz"
I1: "B2M-39.I1.fastq.gz"
I2: "B2M-39.I2.fastq.gz"
# Demultiplexing parameters
skipDemultiplexing : TRUE
# Report
suppFile : FALSE
```
