### ISSUE TITLE
collect_umitags failed with custom I2 pattern

### ISSUE THREAD

**Issue by racng** [cnobles/iGUIDE#92]
I am running the pipeline using already demultiplexed FASTQs. My I2 index file contains just the UMI (8 bp).
I set the following parameters in the config:
```
skipDemultiplexing : TRUE
barcode1Length : 8
barcode2Length : 0
```

I have specified the UMI pattern in barcode 2 field of the sampleInfo.csv

```
sampleName,barcode1,barcode2,gRNA
LK3_5min_oligotag,TAAGGCGA,NNWNNWNN,TRAC;TRBC
```

I get the follow error from rule `collect_umitags`:

```
Trim Inputs:
 Variables           Values                                                                                                                       
 seqFile :           /users/rng/proj/guideseq/iGUIDE/analysis/2025-03-25_nextseq_test/process_data/binned/LK3_5min_oligotag.I2.bin3.fastq.gz      
 output :            /users/rng/proj/guideseq/iGUIDE/analysis/2025-03-25_nextseq_test/process_data/indices/LK3_5min_oligotag.I2.bin3.trim.fastq.gz
 leadTrimSeq :       NNWNNWNN                                                                                                                     
 overTrimSeq :                                                                                                                                    
 phasing :           0                                                                                                                            
 maxMismatch :                                                                                                                                    
 leadMismatch :      0                                                                                                                            
 overMismatch :      0                                                                                                                            
 overMaxLength :     20                                                                                                                           
 overMinLength :     3                                                                                                                            
 minSeqLength :      0                                                                                                                            
 collectRandomIDs :  /users/rng/proj/guideseq/iGUIDE/analysis/2025-03-25_nextseq_test/process_data/indices/LK3_5min_oligotag.bin3.umitags.fasta.gz
 noFiltering :       FALSE                                                                                                                        
 noQualTrimming :    TRUE                                                                                                                         
 badQualBases :      5                                                                                                                            
 qualSlidingWindow : 10                                                                                                                           
 qualThreshold :     ?                                                                                                                            
 stat :              /users/rng/proj/guideseq/iGUIDE/analysis/2025-03-25_nextseq_test/process_data/stats/LK3_5min_oligotag.bin3.umitags.stat      
 compress :          TRUE                                                                                                                         
 cores :             1                                                                                                                            

Input sequence information:
   Reads     Bases Ave.Length
  counts    counts        nts
 440,907 3,527,256          8

Sequence information remaining after minimum length trimming:
   Reads     Bases Ave.Length
  counts    counts        nts
 440,907 3,527,256          8
Error in .normargSEW0(start, "start") : 
  'start' must be a numeric vector (or NULL)
Calls: trimLeading -> <Anonymous> -> solveUserSEW0 -> .normargSEW0
Execution halted
```

Full config file:
``` yaml
# Run configuration
Run_Name : "2025-03-25_nextseq_test"
Sample_Info : "sampleInfo/2025-03-25_nextseq.sampleInfo.csv"
Supplemental_Info : "sampleInfo/2025-03-25_nextseq.supp.csv"
Ref_Genome : "hg38"
Aligner : "blat"
UMItags : TRUE
Abundance_Method : "Fragment"

# Sequence files
Seq_Path : "/users/rng/proj/guideseq/data/2025-03-25_nextseq/demultiplexed"
# R1: "Undetermined_S0_L001_R1_001.fastq.gz"
# R2: "Undetermined_S0_L001_R2_001.fastq.gz"
# I1: "Undetermined_S0_L001_I1_001.fastq.gz"
# I2: "Undetermined_S0_L001_I2_001.fastq.gz"

# SampleInfo formating
Sample_Name_Column : "sampleName"

# Sequence information
R1_Leading_Trim : "."
R1_Overreading_Trim : "GCTCGCGTTTAATTGAGTTGTCATATGT"
R2_Leading_Trim : "ACATATGACAACTCAATTAAAC"
R2_Leading_Trim_ODN : "GCGAGC"
R2_Overreading_Trim : "AGATCGGAAGAGCGTCGTGT"

# Target sequence information, do not include PAM sequence with gRNAs
Target_Sequences:
    TRAC : "GAGAATCAAAATCGGTGAAT"
    TRBC : "GGCTCTCGGAGAATGACGAG"
On_Target_Sites :
    TRAC : "chr14:*:22547576-22547595"
    TRBC'1 : "chr7:*:142791997-142792016"
    TRBC'2 : "chr7:*:142801344-142801363"

# Specimen target treatment
Treatment :
    all : "sampleInfo:gRNA"

# Specimen nuclease treatment
Nuclease :
    all : "Cas9"
    
# Nuclease profile
Nuclease_Profiles :
    Cas9 :
        PAM : "NGG"
        PAM_Loc : "3p"
        PAM_Tol : 1
        Cut_Offset : -4
        Insert_size : FALSE

# ------------------------------------------------------------------------------
# iGUIDE configuration
Read_Types : ["R1", "R2", "I1", "I2"]
Genomic_Reads : ["R1", "R2"]
readNamePattern : "'[\\w\\:\\-\\+]+'"

# Memory Management (in MB units)
defaultMB : 2000
demultiMB : 40000
trimMB : 8000
filtMB : 4000
consolMB : 4000
alignMB : 20000
qualCtrlMB : 16000
assimilateMB : 16000
evaluateMB : 8000
reportMB : 4000

# Demultiplexing parameters
skipDemultiplexing : TRUE
barcode1Length : 8
barcode2Length : 0
barcode1 : "I1"
barcode2 : "I2"
bc1Mismatch : 0
bc2Mismatch : 0
maxNcount : 1

# Sequence trimming
## R1 sequence
R1leadMismatch : 0
R1overMismatch : 4
R1overMaxLength : 20
## R2 sequence
R2leadMismatch : 3
R2odnMismatch : 0
R2overMismatch : 4
R2overMaxLength : 20

# Binning
bins : 3
level : 250

# Reference Alignment
BLATparams : "-tileSize=11 -stepSize=9 -minIdentity=85 -maxIntron=5 -minScore=27 -dots=1000 -out=psl -noHead"
BWAparams : "-k 30 -w 2500 -P -L 25 -a"

# Post-alignment filtering
maxAlignStart : 5
minPercentIdentity : 95
minTempLength : 30
maxTempLength : 2500

# Post-processing
refGenes :
    file : "genomes/hg38.refSeq.ext.nomodel.rds"
    symbolCol : "name2"
oncoGeneList : 
    file : "genomes/allOnco_May2018.tsv"
    symbolCol : "symbol"
specialGeneList : 
    file : "genomes/humanLymph.tsv"
    symbolCol : "symbol"
maxTargetMismatch : 6
upstreamDist : 100
downstreamDist : 30
pileUpMin : 3
recoverMultihits : FALSE

# Report
suppFile : TRUE
tables : FALSE
figures : TRUE
reportData : FALSE
infoGraphic : TRUE
signature : "Rachel Ng [Heath Lab]"
```
